### ISSUE TITLE
Incorrect output in Impacted projects column on redmine 3.2.0

### ISSUE THREAD

**Issue by HighwayStar** [nanego/redmine_multiprojects_issue#11]
Steps to reproduce: install clean redmine 3.2.0

Install redmine_multiproject_issue plugin

List issues in any project with column Impacted projects enabled

![multiproject_issue_impacted_bug](https://cloud.githubusercontent.com/assets/1684100/12443619/abf505fe-bf8b-11e5-9357-900bd81e6bf2.png)

Ipact projects column shows strange records like <Project::ActiveRecord_Associations_CollectionProxy:0x007fe172ec0f80>

**Comment by nanego** [comment]
This bug has been fixed with the last commit.
Please update your plugin and confirm the bug is gone.

Thank you for having reported this.

**Comment by HighwayStar** [comment]
Thank you, issue resolved for me! Impacted projects column now looks good.
