### ISSUE TITLE
Latest commit 367aa63 incompatible with redmine 3.2

### ISSUE THREAD

**Issue by edmcdonagh** [nanego/redmine_multiprojects_issue#20]
As per the comment on commit 367aa63 by @friend-yara, attempting to install this version of the plugin results in the following error:

```
sudo rake redmine:plugins
rake aborted!
NameError: undefined method `user_tracker_permission?' for class `#<Class:0x000000052a53c8>'
/usr/share/redmine/plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:119:in `<class:Issue>'
/usr/share/redmine/plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/redmine/plugins/redmine_multiprojects_issue/init.rb:5:in `block in <top (required)>'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/redmine/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by edmcdonagh** [comment]
As you might expect, installing commit 2fac4fd (i.e. before the last two commits) works fine.

**Comment by jbbarth** [comment]
Indeed this may have broken things, but can you provide some informations about the version of Redmine you're running so we can reproduce/fix it?

**Comment by nanego** [comment]
I have added some tags to specify which version of the plugin should be used, according to your current Redmine version.

When you are running Redmine 3.2 or an older version, you can use the version tagged as v0.2 https://github.com/nanego/redmine_multiprojects_issue/releases/tag/v0.2

**Comment by edmcdonagh** [comment]
Thanks @nanego. Sorry @jbbarth - I've had to turn that server off for a few days due to an air-con issue, so I was just about to check the details when I saw the latest comment.

**Comment by nanego** [comment]
Thanks for updating the Readme file.
