### ISSUE TITLE
Integration in Development Process

### ISSUE THREAD

**Issue by z1gge** [nanego/redmine_multiprojects_issue#25]
Hello nanego,

sorry for writing a ticket, but I've no idea to contact you otherwise. I'm trying to use your plugin and the
scrum plugin (http://www.redmine.org/plugins/scrum-plugin) together, but i missed some little things.

Maybe we can have email contact, so that I can explain my needs and hopefully you have a simple solution for me.

Thank you.

**Comment by nanego** [comment]
Hello

I have never used this plugin with the "scrum" plugin. But please feel free to detail your issue and we will see if we can find a solution.

All the best,
Vincent

**Comment by z1gge** [comment]
Hello Vincent,

thank ou for your fast reply. This is no issue... it is a customisation.
We want to use redmine for our Dev-Teams & for Project Management, too.

The scene is:

In a customer project a project manager creates a feature and then uses the
multi_project_issue_plugin to send
this feature in the backlog of a dev-team. Thats it.

main requirements for custom multi_project_issue_plugin:
- only one more project to select
- when the issue is stored, the sprint_id from the backlog-sprint (backlog
is used as name) of the selected project is




​



2017-01-16 15:06 GMT+01:00 vrobert <notifications@github.com>:

**Comment by z1gge** [comment]
Hello Vincent,

thank ou for your fast reply. This is no issue... it is a customisation.
We want to use redmine for our Dev-Teams & for Project Management, too.

The scene is:

In a customer project a project manager creates a feature and then uses the
multi_project_issue_plugin to send
this feature in the backlog of a dev-team. Thats it.

main requirements for custom multi_project_issue_plugin:
- only one more project to select
- when the issue is stored, the sprint_id from the backlog-sprint (backlog
is used as name) of the selected project is
 stored in the sprint_id column of the issue.
- the same workflow if the extra project is changed in this issue
​



That's all. I hope this is not to complex to implement. What do you think?

Best Regards,

Ronny


PS.: Sorry, because the 2 mails... I hit tab and enter and the message was
send :(




2017-01-17 9:07 GMT+01:00 woody wurst <woody.wurst@gmail.com>:

**Comment by z1gge** [comment]
Hello,

my little picture was lost.

![unnamed](https://cloud.githubusercontent.com/assets/24296056/22194910/691ac0e8-e145-11e6-8a49-82dd82d31adf.png)

Is it possible for you to do this customization? Or can give me a starting point, because I have no redmine development enviroment and have no glue to set it up... 

Best Regards
Ronny

**Comment by nanego** [comment]
Hi Ronny
I think you could easily do this by using an "after_save" callback in the Issue model (app/model/issue.rb).
Please have a try and let me know how you did it.

**Comment by z1gge** [comment]
Hello Vincent,

thank you for this tip. But I have no glue of redmine development/ ruby on rails. So thats the reason why I asked you. I hoped that you can do this customization. Because you have developed this cool plugin and know it best.

But if you have tips for me to setup a debuggable redmine development system, that would be nice.

Best regards
Ronny

**Comment by z1gge** [comment]
Hi,

I've done it :)
Thanks for your tip, I used the before_save hook in the issue_patch to set the field.
 Was not so difficult, the only thing which takes the most time to setup the dev-enviroment.

I used Visual Studio Code for debugging... really nice.

Best Regards,
Ronny
