### ISSUE TITLE
export to pdf

### ISSUE THREAD

**Issue by cukal** [nanego/redmine_multiprojects_issue#31]
Exporting an issue list with related projects column generates a pdf but it shows this in the related project column:
```
#<Project::ActiveRecord_Associations_CollectionProxy:0x007f70098cd568>
```
This does not happen when exporting to CSV.

**Comment by nanego** [comment]
I have fixed this bug today with the last commit.
Can you please confirm everything works as expected?

**Comment by cukal** [comment]
Confirmed working! 

Thanks!
