### ISSUE TITLE
Compatibility with Redmine 3.4.2.stable

### ISSUE THREAD

**Issue by keithkuk** [nanego/redmine_multiprojects_issue#35]
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/html/redmine/lib/redmine/plugin.rb:123:in `find'
/var/www/html/redmine/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
/var/www/html/redmine/plugins/redmine_multiprojects_issue/init.rb:20:in `block in <top (required)>'
/var/www/html/redmine/lib/redmine/plugin.rb:75:in `instance_eval'
/var/www/html/redmine/lib/redmine/plugin.rb:75:in `register'
/var/www/html/redmine/plugins/redmine_multiprojects_issue/init.rb:13:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/www/html/redmine/lib/redmine/plugin.rb:146:in `each'
/var/www/html/redmine/lib/redmine/plugin.rb:146:in `load'
/var/www/html/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/www/html/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

Are there any plans to update the themes to Redmine 3.4.2.stable ?

Thanks a lot for your work.

**Comment by nanego** [comment]
I have recently updated this plugin. The current "preprod" branch should be compatible with Redmine 3.4.2 and I will soon merge it to master.

However the error message is not related to the new Redmine version. It tells a plugin is missing and you will have to install Deface plugin https://github.com/jbbarth/redmine_base_deface
