### ISSUE TITLE
Error 404 - configuration of the plugin

### ISSUE THREAD

**Issue by mbalecr7** [nanego/redmine_multiprojects_issue#39]
Hello,

First thanks for this plugin,  but i just install it and i don't know why , when i go on  /administration/plugin/Redmine Multiple Projects per Issue plugin and then configurate.

Redmine returns me this error : 

"404
La page à laquelle vous souhaitez accéder n'existe pas ou a été supprimée."
( it means the page that you would access don't exist or has been delete)

Redmine Version : 3.2 

i have installed the correct release for my version and redmine_base_deface.

Best regard's 

Mickael

**Comment by nanego** [comment]
Hi Mickael
Do you have any log to share?
Note that the settings on this page are not mandatory. If you don't change them, the plugin should still work well.

**Comment by ToniIltanen** [comment]
You can find the plugin settings at [youdomain]/settings/plugin/redmine_multiprojects_issue
 or
Administration => Plugins => Redmine Multiple Projects per Issue plugin
 => configure

It the plugin is not listed, have you followed the directions correctly (added the plugin to the plugin folder and runned the migrations to the db)
