### ISSUE TITLE
Not bug, but the depends 'redmine_base_deface' does not support 3.4+ 

### ISSUE THREAD

**Issue by remembercode** [nanego/redmine_multiprojects_issue#43]
This is not bug...
And, the depends 'redmine_base_deface' does not support 3.4+
so sad.

**Comment by nanego** [comment]
Hello
Why do you think the base-deface plugin does not support 3.4+?

**Comment by remembercode** [comment]
Well...
the story is,  i am working on bitnami redmine 3.4.6-1
try to install base-deface before multi-projects.
but, failed
the error msg like: rake version ???.... , and the bundle exec also failed. 
try to upgrade rake , but still failed when merging db...

**Comment by nanego** [comment]
Well, I don't know how to help you here. I currently use these plugins in production, with Redmine 3.4

**Comment by nanego** [comment]
Did you run "bundle install" after installing the deface plugin?

**Comment by remembercode** [comment]
Well , thks any way! laf .
i think maybe some days later , it would be ok? 
It is not essential to have one.
thks again ! i will close this issue.
