### ISSUE TITLE
Error to_param on install

### ISSUE THREAD

**Issue by mverberg** [nanego/redmine_multiprojects_issue#45]
After installing the plugin in Redmine 4.0.1 on Rails 5.2.2 and Ruby 2.5.3 using Mysql2:

bundle exec rake redmine:plugins:migrate RAILS_ENV=production

--
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param
/home/redmine/live/plugins/redmine_multiprojects_issue/init.rb:3:in `<top (required)>'
/home/redmine/live/lib/redmine/plugin.rb:173:in `block in load'
/home/redmine/live/lib/redmine/plugin.rb:164:in `each'
/home/redmine/live/lib/redmine/plugin.rb:164:in `load'
/home/redmine/live/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/live/config/environment.rb:14:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
--

I found that the alias_method_chain is depreceated and have to be replaced.
I really like to use your plugin, can you fix the bug?

with kind regards,
Marcel

**Comment by nanego** [comment]
Hello
The plugin has been migrated to Redmine 4.
I think you are not using the latest version.
Can you pull last commits and retry?

**Comment by mverberg** [comment]
Hi, I'm using your v3.4.6 from 31 Oct 2018, is that the latest release?

**Comment by nanego** [comment]
v3.4.6 is the latest release for Redmine 3. You should use the master branch with Redmine 4.

**Comment by mverberg** [comment]
After pulling the master branch, I got the errors below:

rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/home/redmine/live/lib/redmine/plugin.rb:141:in `find'
/home/redmine/live/lib/redmine/plugin.rb:270:in `requires_redmine_plugin'
/home/redmine/live/plugins/redmine_multiprojects_issue/init.rb:19:in `block in <top (required)>'
/home/redmine/live/lib/redmine/plugin.rb:92:in `instance_eval'
/home/redmine/live/lib/redmine/plugin.rb:92:in `register'
/home/redmine/live/plugins/redmine_multiprojects_issue/init.rb:12:in `<top (required)>'
/home/redmine/live/lib/redmine/plugin.rb:173:in `block in load'
/home/redmine/live/lib/redmine/plugin.rb:164:in `each'
/home/redmine/live/lib/redmine/plugin.rb:164:in `load'
/home/redmine/live/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/live/config/environment.rb:14:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by nanego** [comment]
Please follow these steps to install the plugin:
https://github.com/nanego/redmine_multiprojects_issue#installation

**Comment by mverberg** [comment]
Hi , the installation stept were succesful, I now run your plugin, thanks!
