### ISSUE TITLE
Plugin compatibility with Redmine 4.2

### ISSUE THREAD

**Issue by tantic** [nanego/redmine_multiprojects_issue#51]
Hello,

thanks for your plugin, very useful.
This morning i tried to upgrade Redmine to version 4.2 but i have some errors.

```
NoMethodError (undefined method `where' for #<Proc:0x0000558422692548>
Did you mean?  when):
  
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/acts_as_activity_provider.rb:27:in `find_events'
lib/redmine/activity/fetcher.rb:93:in `block (2 levels) in events'
lib/redmine/activity/fetcher.rb:92:in `each'
lib/redmine/activity/fetcher.rb:92:in `block in events'
lib/redmine/activity/fetcher.rb:91:in `each'
lib/redmine/activity/fetcher.rb:91:in `events'
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/activity_fetcher_patch.rb:6:in `events'
app/controllers/activities_controller.rb:58:in `index'
```

Maybe due to the patch https://www.redmine.org/issues/33664?

Thanks

**Comment by nanego** [comment]
Hello @tantic 
Thanks for reporting the issue.
I plan to make this plugin compatible with Redmine 4.2.0 in the next weeks.
Please feel free to submit a pull request if you want to contribute on this task.

**Comment by tantic** [comment]
Thanks @nanego, no hurry, it was just for the report. I'll see if i can help

**Comment by CubaLibre84** [comment]
Hi. I have the exact same problem (internal error if I click on "activity"). When do you think to fix this? Thanks!

**Comment by Alexey-I** [comment]
This is also relevant for me.

**Comment by nanego** [comment]
The plugin is now fully compatible with Redmine 4.2
Please have a look, and let me know if there is any issue.

**Comment by CubaLibre84** [comment]
I just tested the latest version of the plugin with Redmine 4.1.2 and it works like a charm. Thank you very much!!!

**Comment by tantic** [comment]
Hello,

I can confirm that it works for me toi, thanks very much
