### ISSUE TITLE
Unable to open issue page and an activiti page

### ISSUE THREAD

**Issue by kyvaith** [nanego/redmine_multiprojects_issue#56]
`ActionView::Template::Error (super: no superclass method show_detail' for #<#<Class:0x000056271a9ed210>:0x00007f855270efc0>
Did you mean?  show_value):
    19: 
    20:     <% if journal.details.any? %>
    21:     <ul class="details">
    22:       <% details_to_strings(journal.visible_details).each do |string| %>
    23:        <li><%= string %></li>
    24:       <% end %>
    25:     </ul>
  `

**Comment by nanego** [comment]
Not enough details. I close this.
