### ISSUE TITLE
Unable to open issue page and an activity page

### ISSUE THREAD

**Issue by kyvaith** [nanego/redmine_multiprojects_issue#57]
After installing the plugin and dependences, everything works, except I'm unable to open certain issues and activity page. Error log:

[1;32mDeface:[0m 'disable_project_link_if_current_user_cannot_open_it' matched 0 times with 'table.list.issues tbody tr'
[1;32mDeface: [ERROR][0m The original source for 'show-projects-in-issue-description' has changed, this override should be reviewed to ensure it's still valid.
[1;32mDeface: [ERROR][0m The original source for 'add-multiple-projects-to-issue-form' has changed, this override should be reviewed to ensure it's still valid.
  
ActionView::Template::Error (super: no superclass method `show_detail' for #<#<Class:0x000056321d88d088>:0x0000563222202a60>
Did you mean?  show_value):
    19: 
    20:     <% if journal.details.any? %>
    21:     <ul class="details">
    22:       <% details_to_strings(journal.visible_details).each do |string| %>
    23:        <li><%= string %></li>
    24:       <% end %>
    25:     </ul>
  
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issues_helper_patch.rb:53:in `show_detail'
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issues_helper_patch.rb:53:in `show_detail'
app/helpers/issues_helper.rb:494:in `block in details_to_strings'
app/helpers/issues_helper.rb:480:in `each'
app/helpers/issues_helper.rb:480:in `details_to_strings'
app/views/issues/tabs/_history.html.erb:22:in `block in _8c956b192a709ba8e84f95f289716173'
app/views/issues/tabs/_history.html.erb:7:in `each'
app/views/issues/tabs/_history.html.erb:7:in `_8c956b192a709ba8e84f95f289716173'
plugins/that_thread/app/views/issues/tabs/_history.html.erb:5:in `_d27ba65f6584cbefb88dae0cdae0cc4a'
app/views/common/_tabs.html.erb:21:in `block in _edbe8cba465e1fb61be17275f584bf56'
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20:in `_edbe8cba465e1fb61be17275f584bf56'
app/helpers/application_helper.rb:481:in `render_tabs'
app/views/issues/show.html.erb:144:in `_5a981755fabd88113545d3a216f106b5'
app/controllers/issues_controller.rb:112:in `block (2 levels) in show'
app/controllers/issues_controller.rb:104:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by nanego** [comment]
Can you please give more details about your Redmine version and any other installed plugins? (see the information page in Admin panel)

**Comment by kyvaith** [comment]
Sure:

Informacje
Redmine 4.2.3.stable
Zmieniono domyślne hasło administratora	
Zapisywalne repozytorium plików	
Zapisywalny katalog zasobów wtyczek (./public/plugin_assets)	
MiniMagick dostępne (opcjonalnie)	
Konwersja przez ImageMagick dostępna (optional)	
ImageMagick PDF support available (optional)	

Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.6.9-p207 (2021-11-24) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Cvs                            1.12.13
  Bazaar                         2.8.0
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.2
  redmine_all_thumbnails         1.0.5
  redmine_autoclose              0.0.8
  redmine_base_deface            1.5.3
  redmine_base_stimulusjs        1.1.1
  redmine_checklists             3.1.19
  redmine_contacts               4.3.4
  redmine_contacts_helpdesk      4.1.12
  redmine_default_assignee       1.2.0
  redmine_drive                  1.1.1
  redmine_favorite_projects      2.1.1
  redmine_finance                2.1.7
  redmine_home_page_redirector   1.0.0
  redmine_impersonate            2.0.0
  redmine_issue_dynamic_edit     0.7.2
  redmine_logs                   0.2.0
  redmine_more_previews          2.0.7
  redmine_multiprojects_issue    4.1.1
  redmine_my_page                0.1.13
  redmine_people                 1.6.1
  redmine_preview_inline         1.0.3
  redmine_products               2.1.2
  redmine_questions              1.0.2
  redmine_reporter               2.0.0
  redmine_resources              1.0.5
  redmine_theme_changer          0.4.0
  redmine_zenedit                2.0.2
  that_thread                    0.0.1

**Comment by nanego** [comment]
Oh, that's a lot of plugins. The issue must come from an incompatibility with one of these plugins. But I don't know which one.
If you can temporarily remove some, you may be able to find which one is incompatible with the multi-projects plugin.
