### ISSUE TITLE
Not working with Redmine 5.0.1

### ISSUE THREAD

**Issue by tilman19** [nanego/redmine_multiprojects_issue#61]
Hello,
sadly this plugin is not yet working with the latest version of Redmine. I tried to adjust some stuff to the Rails 6 and zeitgeist but as I’m not a pro in Ruby its not full working and I can’t open the list of projects to add more projects to the ticket. The trouble seems to be with authorization. 
Will add my changes as pull request and I would be very happy if someone could support me with the final fixes. Thank you!

**Comment by qlefevre** [comment]
+1 
@nanego Do you need help to upgrade the plugin to redmine 5.0.1?
I also live in Lille if you want to discuss about it.

**Comment by nanego** [comment]
Hello
This plugin is not yet compatible with Redmine 5. 
But I plan to update it in a few weeks.

**Comment by nanego** [comment]
Hello
The plugin is now compatible with Redmine 5.
Please give it a try, and let me know if there is any issue with this new release.

**Comment by qlefevre** [comment]
Hello nanego,

Thank you for this great work !

However I have a small problem with the redmine_base_stimulusjs plugin, I opened a pull request : https://github.com/nanego/redmine_base_stimulusjs/pull/3
I found a similar problem in the redmine_base_deface plugin, and you seem to have rights on it : https://github.com/jbbarth/redmine_base_deface/pull/13

What bothers me the most is the redmine_base_deface plugin, but you may have the solution:

/usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get': uninitialized constant Issues::Form (NameError)

    parent.const_get(cname, false)
          ^^^^^^^^^^

from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'

Do you have any advice?

I wish you a nice day,
Quentin

**Comment by nanego** [comment]
We still have some errors in production mode, when using Zeitwerk eager-loading.
I'm working on it.
