### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by lremy** [nanego/redmine_multiprojects_issue#7]
I tried to install the plugin on redmine 2.5.1, and faced several problems, essentially due to external plugin requirements.

Maybe it could be great to update installation description, and add links to the two plugins that are required?
- redmine_base_deface
- redmine_base_select2

Thanks!

**Comment by nanego** [comment]
Required plugins are currently listed in the Readme file, under the Installation section.
Can you please check this section and tell me if any information is missing?

**Comment by lremy** [comment]
Correct, there are listed on github!
I only checked the redmine plugin page http://www.redmine.org/plugins/redmine_multiprojects_issue .
Possible to update it?

**Comment by nanego** [comment]
The Redmine plugin page has been updated. Thank you for the feedback.
