### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by lremy** [nanego/redmine_multiprojects_issue#8]
Once installed, I checked the plugin configuration. The plugin asks for a custom field to quickly select projects.

What kind of custom field is needed there?
I tried a text field or an integer field for object type issues, but did not succeed to select multiple projects for one issure (new or already existing).

Could you give some explanation on the plugin configuration?

Thanks!

**Comment by nanego** [comment]
Actually, the plugin does not need any configuration.
In the settings, you can specify some custom fields, but they are only used as filters in the modal window where you can select projects (by default, there is only two filters used to select multiple project at once: all or nothing).

**Comment by lremy** [comment]
Ok, I understand.
But I still have a problem: I don't have the "Impacted projects" zone on my issues, that we can show on the screenshots. Neither when viewing an issue, nore when updating it.
Any idea?

**Comment by lremy** [comment]
hi there, any update on my problem?

**Comment by manuelcanga** [comment]
I don't have the "Impacted projects" zone on my issues. I have a Redmine 2.4.x

**Comment by manuelcanga** [comment]
I think deface plugin not working

**Comment by ddk85** [comment]
Same problems for me...

**Comment by nanego** [comment]
I tried to reproduce the problem, without success.
![capture d ecran 2015-05-20 a 14 31 30](https://cloud.githubusercontent.com/assets/1620522/7725664/00524f58-fefd-11e4-80aa-b42ff01f76ab.png)

This screenshot has been made using a fresh install of Redmine 2.4-stable.

Can you please help me to reproduce this bug?

**Comment by ddk85** [comment]
My apologies, it was my mistake. All works great.

2015-05-20 15:33 GMT+03:00 vrobert <notifications@github.com>:

**Comment by lremy** [comment]
I tried it with a 2.5.1.stable version of redmine.
![redmine_version](https://cloud.githubusercontent.com/assets/11176362/7726657/ca2d34c2-ff03-11e4-97d4-793fd2663f1f.PNG)

Here is a screenshot of a new issue, where I have no "Impacted projects" field.
![newissue](https://cloud.githubusercontent.com/assets/11176362/7726661/d14ec54a-ff03-11e4-9c51-4ff61e8970cd.PNG)

But... I don't know what is wrong:)
How can I help?

**Comment by nanego** [comment]
Did you try to temporarily remove all plugins except multiproject, deface and select2?
This way, we could be sure that there is no conflict with other plugins.

**Comment by SkolVikingsGuy** [comment]
![screenshot 2015-12-03 15 22 45](https://cloud.githubusercontent.com/assets/6402394/11574545/e5fa9474-99d1-11e5-91e7-ea3caffb9ac9.png)

Our list of projects runs off the bottom of the Projects dialog.  Any ideas?

**Comment by nanego** [comment]
I think you are using a theme which has never been tested with this plugin.

**Comment by SkolVikingsGuy** [comment]
It was the theme - works with the default theme.  Also worked with the other theme in Firefox or Windows Explorer.  Thanks.
