### ISSUE TITLE
PluginNotFound

### ISSUE THREAD

**Issue by aozhi2nd** [nanego/redmine_multiprojects_issue#9]
bash-4.1# rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/redmine-2.6.2-0/apps/redmine/htdocs)
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:118:in `find'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:246:in `requires_redmine_plugin'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/plugins/redmine_multiprojects_issue/init.rb:18:in `block in <top (required)>'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `instance_eval'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `register'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/plugins/redmine_multiprojects_issue/init.rb:11:in `<top (required)>'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in `block in load'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `each'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `load'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/config/initializers/30-redmine.rb:19:in `<top (required)>'
/opt/redmine-2.6.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by nanego** [comment]
You have to install some other plugins. Please read the README file.
